export const CelularesMockup = [
    {
        id: 1,
        modelo: "Galaxy s23 ultra ",
        marca: "Samsung",
        precio: 800,
        almacenamiento: 256,
        ram: 16,
        sistemaOperativo: "Android",
        color: "Black",
        image: 'celular_1',
        imagen: 'celular_11',
        disponible: true
    },
    {
        id: 2,
        modelo: "Iphone 17 pro",
        marca: "Apple",
        precio: 1300,
        almacenamiento: 1024,
        ram: 32,
        sistemaOperativo: "IOS",
        color: "Orange",
        image: 'celular_2',
        imagen: 'celular_22',
        disponible: true
    },
    {
        id: 3,
        modelo: "Iphone 16",
        marca: "Apple",
        precio: 900,
        almacenamiento: 256,
        ram: 16,
        sistemaOperativo: "IOS",
        color: "Pink",
        image: 'celular_3',
        imagen: 'celular_33',
        disponible: true
    },
    {
        id: 4,
        modelo: "Redmi 14 pro",
        marca: "Xiaomi",
        precio: 400,
        almacenamiento: 128,
        ram: 8,
        sistemaOperativo: "Android",
        color: "Skyblue",
        image: 'celular_4',
        imagen: 'celular_44',
        disponible: true
    },
    {
        id: 5,
        modelo: "Galaxy Z Flip",
        marca: "Samsung",
        precio: 900,
        almacenamiento: 256,
        ram: 16,
        sistemaOperativo: "Android",
        color: "White",
        image: 'celular_5',
        imagen: 'celular_55',
        disponible: true
    },
    {
        id: 6,
        modelo: "Iphone 15 Pro Max",
        marca: "Apple",
        precio: 1000,
        almacenamiento: 256,
        ram: 16,
        sistemaOperativo: "IOS",
        color: "Grey",
        image: 'celular_6',
        imagen: 'celular_66',
        disponible: true
    },
    {
        id: 7,
        modelo: "Galaxy s25",
        marca: "Samsung",
        precio: 1000,
        almacenamiento: 256,
        ram: 16,
        sistemaOperativo: "Android",
        color: "white",
        image: 'celular_7',
        imagen: 'celular_77',
        disponible: true
    },
    {
        id: 8,
        modelo: "Iphone 13 pro",
        marca: "Apple",
        precio: 600,
        almacenamiento: 128,
        ram: 6,
        sistemaOperativo: "IOS",
        color: "Skyblue",
        image: 'celular_8',
        imagen: 'celular_88',
        disponible: true
    }
]